include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_redundant_argument_values: true
    avoid_print: true
    file_names: true
    invalid_assignment: true
    no_duplicate_case_values: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    sized_box_for_whitespace: true

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
