name: Pull Request Validate
on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Analyzer and Tests
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'
      - run: flutter pub get

      - name: Analyzer and Dart Code Metrics
    # Run flutter analyzer with annotations
        uses: zgosalvez/github-actions-analyze-dart@v2
    # Run DCM rules
      - uses: dart-code-checker/dart-code-metrics-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    # Run all tests
      - name: Tests
        run: |
          flutter test --coverage
  build:
    name: Build app
    needs: [tests]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      # Build for both machines(Android and iOS)
        os: [ubuntu-latest, macos-11]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            build/
            android/.gradle/
          key: ${{ runner.os }}-flutter_ci_example-${{ hashFiles('**/*.gradle*', 'pubspec.lock') }}

      - name: Build Android app
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "Building Android..."
          pwd
          flutter pub get
          flutter build apk --no-pub
          flutter build appbundle --no-pub       
      - name: Build iOS app
        if: ${{ matrix.os == 'macos-11' }}
        run: |
          flutter pub get
          echo "Building iOS..."
          echo "Not implemented yet."
  
      - name: 'Upload Builds'
        uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          retention-days: 5